apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "15s"
    editable: false

  - name: SWMF-Postgres
    type: postgres
    access: proxy
    orgId: 1
    url: postgres:5432
    database: swmf
    user: swmf
    secureJsonData:
      password: swmfpass
    jsonData:
      sslmode: "disable"
      postgresVersion: 1600
      timescaledb: false
    editable: false
