#!/usr/bin/env python3
"""
gen_gannon_placeholder_mhd.py — synthesise a flagged Gannon MHD hindcast
==========================================================================
Reads the page-side Gannon replay bundle
``data/hindcast/gannon_may_2024_replay.json`` and emits an MHD-shaped
hindcast JSON consumable by ``dsmc/pipeline/fit_pseudo_ap.py --hindcast``:

  data/hindcast/gannon_may_2024_hindcast.json

The output carries ``"is_placeholder": true`` at top level. ``fit_pseudo_ap``
refuses to fit against it unless ``--allow-placeholder`` is set; if it is,
the resulting fit JSON inherits ``is_placeholder_input: true`` so any
downstream consumer (validate_density, the page) can refuse to score it as
a real result. This mirrors the contract on the features-CSV side.

The point of this file is to exercise the MHD-track pipeline end-to-end
*before* the real BATS-R-US run lands, the same way
``dsmc/raw/supermag/gannon_may_2024_PLACEHOLDER.csv`` exercises the
ground-mag path. Replace the output with the real
hindcast_runner.py emission when BATS-R-US for Gannon completes.

Why a script instead of a checked-in JSON
-----------------------------------------
The real BATS-R-US output will overwrite this file in-place at
``data/hindcast/gannon_may_2024_hindcast.json``. Keeping the file
gitignored and the *generator* tracked avoids merge friction the moment
the real data lands; anyone can regenerate the placeholder at any time
by running this script.

Usage
-----
  python3 scripts/gen_gannon_placeholder_mhd.py
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
REPLAY = REPO / "data" / "hindcast" / "gannon_may_2024_replay.json"
OUT    = REPO / "data" / "hindcast" / "gannon_may_2024_hindcast.json"

# 5-minute cadence to match the real BATS-R-US IE-log emission cadence.
OUT_CADENCE_MIN = 5


def _interp(xs: list[float], frac: float) -> float:
    """Linear interpolate hourly array `xs` at fractional sample position."""
    if frac <= 0:
        return float(xs[0])
    if frac >= len(xs) - 1:
        return float(xs[-1])
    lo = int(frac)
    hi = lo + 1
    t = frac - lo
    return xs[lo] * (1 - t) + xs[hi] * t


def main() -> int:
    replay = json.loads(REPLAY.read_text())
    window = replay["window"]
    t_start = datetime.fromisoformat(window["start"].replace("Z", "+00:00"))
    t_end   = datetime.fromisoformat(window["end"].replace("Z", "+00:00"))
    step_min = window["step_minutes"]            # 60 in the placeholder

    phi_arr = replay["drivers_compact"]["phi_pc_kv"]
    hpi_arr = replay["drivers_compact"]["hpi_gw"]
    n_hourly = len(phi_arr)
    expected_h = int((t_end - t_start).total_seconds() // (step_min * 60)) + 1
    assert n_hourly == expected_h, f"replay drivers length {n_hourly} != expected {expected_h}"

    # Emit at 5-min cadence by linear interpolation between hourly anchors.
    out_dt = timedelta(minutes=OUT_CADENCE_MIN)
    total_seconds = int((t_end - t_start).total_seconds())
    n_out = total_seconds // (OUT_CADENCE_MIN * 60) + 1

    samples = []
    for i in range(n_out):
        t = t_start + i * out_dt
        # Position on the hourly grid (e.g. 12.5 means halfway between hour-12 and hour-13).
        elapsed_min = i * OUT_CADENCE_MIN
        frac = elapsed_min / step_min
        samples.append({
            "t":         t.isoformat().replace("+00:00", "Z"),
            "phi_pc_kv": round(_interp(phi_arr, frac), 3),
            "hpi_gw":    round(_interp(hpi_arr, frac), 3),
        })

    payload = {
        "event_id":         "gannon_may_2024",
        "label":            "May 2024 Gannon Superstorm (G5) — PLACEHOLDER",
        "storm_class":      "G5",
        "window_utc":       [
            t_start.isoformat().replace("+00:00", "Z"),
            t_end.isoformat().replace("+00:00", "Z"),
        ],
        "cadence_minutes":  OUT_CADENCE_MIN,
        "source":           "placeholder-from-replay-bundle",
        "is_placeholder":   True,
        "_warning":         (
            "Synthetic MHD output generated by "
            "scripts/gen_gannon_placeholder_mhd.py from the page-side "
            "Gannon replay bundle. NOT BATS-R-US output. fit_pseudo_ap.py "
            "refuses to fit this unless --allow-placeholder is passed; "
            "any resulting fit carries is_placeholder_input=true so the "
            "validator and the page can refuse to score it as real."
        ),
        "regression":       {"version": "n/a-placeholder", "formula": "—"},
        "samples":          samples,
        "generated_utc":    datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z"),
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2))
    print(f"wrote {OUT} ({len(samples)} samples, "
          f"phi_pc_kv peak {max(s['phi_pc_kv'] for s in samples):.0f} kV, "
          f"hpi_gw peak {max(s['hpi_gw'] for s in samples):.0f} GW)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
